### ISSUE TITLE
Lines are read only whn processes closes pipe

### ISSUE THREAD

**Issue by oridag** [logstash-plugins/logstash-input-pipe#15]
Running on Ubuntu 16.04, no events are read from the pipe before the pipe is closed (e.g. process exits). This makes this plugin unusable as (according the documentation) it is supposed to be used with long running processes

**Comment by guyboertje** [comment]
@oridag 

Please confirm that this is limited to Ubuntu 16.04. Have you tried your config on OSX for example?

How does the pipe close in your setup? It is not clear whether you are using this plugin for long or short running processes.

Please confirm that your events are separated by newline characters.
The [code](https://github.com/logstash-plugins/logstash-input-pipe/blob/master/lib/logstash/inputs/pipe.rb#L47) is only set to emit an event for each line (text + newline)

**Comment by jordansissel** [comment]
@oridag can you explain how you observed this? Many programs will buffer their writes and only flush to the actual output file descriptor when that buffer is full -- and for some programs, this means that writes to the underlying file descriptor only will occur when the program terminates.

Can you attach your configuration?

**Comment by oridag** [comment]
@guyboertje @jordansissel 

I was probably to quick to open this issue. The problem currently seems to be something specific to my implementation. My appologies, will close it for now
